/**
 * NeryvaHostedPage — full-screen tenant-branded chat page (P7-2, Arch §5).
 *
 * Reuses the widget's session-token + SSE engine in a full-page layout.
 * The tenant can point their own domain/subdomain at this page.
 *
 * Configuration is read from:
 *   1. URL query params: ?tenant=acme&tenant_id=t_abc&surface_id=s_sales
 *   2. A global `window.__NERYVA_CONFIG__` object (set by the tenant's server)
 *   3. A `<meta name="neryva:*">` tag on the host page
 *
 * This supports multi-device continuity: the session token and end-user
 * identity are stable per device (localStorage), so conversations resume
 * across page reloads and devices (Arch §6.4).
 */

import {
  bootstrapSessionToken,
  streamMessage,
  submitFeedback,
  type SessionTokenResult,
} from '../api/client';
import {
  appendMessage,
  createBudgetErrorBubble,
  createErrorBubble,
  createMessage,
  updateLastMessage,
  type ChatMessage,
} from '../state/messages';

// ---------------------------------------------------------------------------
// Config resolution
// ---------------------------------------------------------------------------

interface HostedPageConfig {
  tenant: string;
  tenantId: string;
  surfaceId?: string;
  apiBase: string;
  title: string;
  accentColor: string;
  disclosure: string;
  maxInputLength: number;
  logoUrl?: string;
}

declare global {
  interface Window {
    __NERYVA_CONFIG__?: Partial<HostedPageConfig>;
  }
}

function resolveConfig(): HostedPageConfig {
  const params = new URLSearchParams(window.location.search);
  const global = window.__NERYVA_CONFIG__ ?? {};

  const meta = (name: string): string | undefined => {
    const el = document.querySelector(`meta[name="neryva:${name}"]`);
    return el?.getAttribute('content') ?? undefined;
  };

  return {
    tenant: params.get('tenant') ?? global.tenant ?? meta('tenant') ?? '',
    tenantId: params.get('tenant_id') ?? global.tenantId ?? meta('tenant-id') ?? '',
    surfaceId: params.get('surface_id') ?? global.surfaceId ?? meta('surface-id'),
    apiBase: (params.get('api_base') ?? global.apiBase ?? meta('api-base') ?? '/api').replace(/\/$/, ''),
    title: params.get('title') ?? global.title ?? meta('title') ?? 'Chat',
    accentColor: params.get('accent') ?? global.accentColor ?? meta('accent-color') ?? '#2563eb',
    disclosure:
      global.disclosure ??
      meta('disclosure') ??
      'You are chatting with an AI assistant. Responses are generated by artificial intelligence.',
    maxInputLength: parseInt(params.get('max_length') ?? '', 10) || global.maxInputLength || 2000,
    logoUrl: global.logoUrl ?? meta('logo-url'),
  };
}

// ---------------------------------------------------------------------------
// Hosted page renderer
// ---------------------------------------------------------------------------

export class NeryvaHostedPage {
  private config: HostedPageConfig;
  private messages: ChatMessage[] = [];
  private sending = false;
  private sessionId: string;
  private sessionToken: SessionTokenResult | null = null;
  /** Backend thread id from the last completed turn (used for feedback). */
  private currentThreadId: string | null = null;

  private root: HTMLElement;
  private listEl!: HTMLDivElement;
  private inputEl!: HTMLInputElement;
  private charCountEl!: HTMLSpanElement;
  private sendBtnEl!: HTMLButtonElement;

  constructor(rootElement: HTMLElement) {
    this.root = rootElement;
    this.config = resolveConfig();
    this.sessionId =
      typeof crypto !== 'undefined' && 'randomUUID' in crypto
        ? crypto.randomUUID()
        : `session-${Date.now()}`;
  }

  async mount(): Promise<void> {
    this.renderPage();
    // Eagerly bootstrap the session token
    try {
      await this.ensureToken();
    } catch {
      // Token will be re-attempted on first message
    }
  }

  // -----------------------------------------------------------------------
  // Token management
  // -----------------------------------------------------------------------

  private async ensureToken(): Promise<SessionTokenResult> {
    if (this.sessionToken) return this.sessionToken;
    this.sessionToken = await bootstrapSessionToken({
      apiBase: this.config.apiBase,
      tenantId: this.config.tenantId,
      surfaceId: this.config.surfaceId,
    });
    return this.sessionToken;
  }

  // -----------------------------------------------------------------------
  // Message handling
  // -----------------------------------------------------------------------

  async sendMessage(text: string): Promise<void> {
    const message = text.trim();
    if (!message || this.sending) return;

    if (message.length > this.config.maxInputLength) {
      this.showError(`Message exceeds the ${this.config.maxInputLength} character limit.`);
      return;
    }

    if (!this.config.tenant || !this.config.tenantId) {
      this.showError('Chat configuration is incomplete. Please contact the site administrator.');
      return;
    }

    let token: SessionTokenResult;
    try {
      token = await this.ensureToken();
    } catch (err) {
      this.showError(err instanceof Error ? err.message : 'Session initialization failed');
      return;
    }

    this.sending = true;
    this.messages = appendMessage(this.messages, createMessage('user', message));
    this.messages = appendMessage(this.messages, createMessage('assistant', '', true));
    this.inputEl.value = '';
    this.updateCharCount();
    this.renderMessages();
    this.updateSendButton();

    streamMessage({
      apiBase: this.config.apiBase,
      tenantSlug: this.config.tenant,
      token: token.token,
      message,
      sessionId: this.sessionId,
      surfaceId: this.config.surfaceId,

      onDelta: (delta) => {
        this.messages = updateLastMessage(this.messages, (msg) => ({
          ...msg,
          content: msg.content + delta,
          streaming: true,
        }));
        this.renderMessages();
      },

      onSession: ({ threadId }) => {
        if (threadId) this.currentThreadId = threadId;
      },

      onRedaction: (text: string) => {
        // Output moderation retracted already-released deltas: replace the
        // streamed content with the safe remainder.
        this.messages = updateLastMessage(this.messages, (msg) => ({
          ...msg,
          content: text,
          streaming: true,
        }));
        this.renderMessages();
      },

      onComplete: (result) => {
        this.sending = false;
        this.sessionId = result.sessionId || this.sessionId;
        if (result.threadId) this.currentThreadId = result.threadId;
        this.messages = updateLastMessage(this.messages, (msg) => ({
          ...msg,
          content: result.response || msg.content,
          streaming: false,
        }));
        this.renderMessages();
        this.updateSendButton();
        this.inputEl.focus();
      },

      onError: (err) => {
        this.sending = false;
        this.messages = this.messages.filter((m) => !m.streaming);
        this.showError(err.detail, err.budgetRejected);
        if (err.status === 401) this.sessionToken = null;
        this.renderMessages();
        this.updateSendButton();
      },
    });
  }

  private showError(detail: string, budgetRejected = false): void {
    this.messages = appendMessage(
      this.messages,
      budgetRejected ? createBudgetErrorBubble(detail) : createErrorBubble(detail),
    );
  }

  private async handleFeedback(messageId: string, rating: 'up' | 'down'): Promise<void> {
    this.messages = this.messages.map((m) =>
      m.id === messageId ? { ...m, feedback: rating } : m,
    );
    this.renderMessages();

    try {
      const token = await this.ensureToken();
      const threadId = this.currentThreadId;
      if (threadId) {
        await submitFeedback({
          apiBase: this.config.apiBase,
          token: token.token,
          threadId,
          messageId,
          rating,
        });
      }
    } catch {
      // best-effort
    }
  }

  private updateCharCount(): void {
    if (!this.charCountEl || !this.inputEl) return;
    const len = this.inputEl.value.length;
    const max = this.config.maxInputLength;
    this.charCountEl.textContent = `${len}/${max}`;
    this.charCountEl.className =
      'hosted-char-count' + (len > max ? ' over' : len > max * 0.9 ? ' warn' : '');
  }

  private updateSendButton(): void {
    if (this.sendBtnEl) {
      this.sendBtnEl.disabled = this.sending;
    }
  }

  // -----------------------------------------------------------------------
  // Rendering
  // -----------------------------------------------------------------------

  private renderPage(): void {
    const accent = this.config.accentColor;
    this.root.innerHTML = `
      <style>${HOSTED_STYLES(accent)}</style>
      <div class="hosted-container">
        <header class="hosted-header">
          ${this.config.logoUrl ? `<img class="hosted-logo" src="${escapeAttr(this.config.logoUrl)}" alt="Logo" />` : ''}
          <h1 class="hosted-title">${escapeHtml(this.config.title)}</h1>
        </header>

        <main class="hosted-chat" role="log" aria-label="Chat messages" aria-live="polite"></main>

        <footer class="hosted-footer">
          <div class="hosted-disclosure" role="status">${escapeHtml(this.config.disclosure)}</div>
          <form class="hosted-input-row" aria-label="Send a message">
            <label class="sr-only" for="hosted-input">Message</label>
            <input
              id="hosted-input"
              type="text"
              placeholder="Type a message…"
              autocomplete="off"
              maxlength="${this.config.maxInputLength}"
              aria-label="Message"
            />
            <button type="submit" aria-label="Send message">Send</button>
          </form>
          <span class="hosted-char-count" aria-hidden="true">0/${this.config.maxInputLength}</span>
        </footer>
      </div>
    `;

    this.listEl = this.root.querySelector('.hosted-chat') as HTMLDivElement;
    this.inputEl = this.root.querySelector('#hosted-input') as HTMLInputElement;
    this.charCountEl = this.root.querySelector('.hosted-char-count') as HTMLSpanElement;
    this.sendBtnEl = this.root.querySelector('.hosted-input-row button') as HTMLButtonElement;

    this.root.querySelector('.hosted-input-row')!.addEventListener('submit', (e) => {
      e.preventDefault();
      void this.sendMessage(this.inputEl.value);
    });
    this.inputEl.addEventListener('input', () => this.updateCharCount());

    this.renderMessages();
  }

  private renderMessages(): void {
    if (!this.listEl) return;
    this.listEl.innerHTML = '';

    if (this.messages.length === 0) {
      const empty = document.createElement('div');
      empty.className = 'hosted-empty';
      empty.textContent = 'Start a conversation…';
      this.listEl.appendChild(empty);
      return;
    }

    for (const msg of this.messages) {
      const bubble = document.createElement('div');
      const classes = ['hosted-msg', msg.role];
      if (msg.error) classes.push('error');
      if (msg.budget) classes.push('budget');
      if (msg.streaming) classes.push('streaming');
      bubble.className = classes.join(' ');
      bubble.setAttribute('role', 'article');
      bubble.setAttribute('aria-label', `${msg.role} message`);

      const content = document.createElement('span');
      content.textContent = msg.content;
      bubble.appendChild(content);

      // Feedback for assistant (non-error, non-streaming)
      if (msg.role === 'assistant' && !msg.error && !msg.streaming && msg.content) {
        const row = document.createElement('div');
        row.className = 'hosted-feedback-row';

        for (const r of ['up', 'down'] as const) {
          const btn = document.createElement('button');
          btn.className = 'hosted-fb-btn' + (msg.feedback === r ? ' active' : '');
          btn.textContent = r === 'up' ? '👍' : '👎';
          btn.setAttribute('aria-label', r === 'up' ? 'Helpful' : 'Not helpful');
          btn.setAttribute('aria-pressed', String(msg.feedback === r));
          btn.addEventListener('click', () => void this.handleFeedback(msg.id, r));
          row.appendChild(btn);
        }
        bubble.appendChild(row);
      }

      this.listEl.appendChild(bubble);
    }

    if (this.sending && !this.messages.some((m) => m.streaming)) {
      const typing = document.createElement('div');
      typing.className = 'hosted-typing';
      typing.setAttribute('role', 'status');
      typing.textContent = 'Thinking…';
      this.listEl.appendChild(typing);
    }

    this.listEl.scrollTop = this.listEl.scrollHeight;
  }
}

// ---------------------------------------------------------------------------
// Styles — full-page layout
// ---------------------------------------------------------------------------

function HOSTED_STYLES(accent: string): string {
  return `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, -apple-system, sans-serif; }

  .sr-only {
    position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
    overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;
  }

  .hosted-container {
    display: flex; flex-direction: column; height: 100vh;
    max-width: 720px; margin: 0 auto; background: #fff;
  }

  .hosted-header {
    display: flex; align-items: center; gap: 12px;
    padding: 16px 24px; background: ${accent}; color: #fff;
  }
  .hosted-logo { height: 32px; width: auto; border-radius: 6px; }
  .hosted-title { font-size: 18px; font-weight: 600; }

  .hosted-chat {
    flex: 1; overflow-y: auto; padding: 20px 24px;
    display: flex; flex-direction: column; gap: 12px;
    background: #f9fafb; scroll-behavior: smooth;
  }

  .hosted-empty {
    margin: auto; color: #9ca3af; font-size: 15px; text-align: center;
  }

  .hosted-msg {
    max-width: 75%; padding: 12px 16px; border-radius: 14px;
    font-size: 14px; line-height: 1.55; white-space: pre-wrap;
    word-break: break-word;
  }
  .hosted-msg.user {
    align-self: flex-end; background: ${accent}; color: #fff;
    border-bottom-right-radius: 4px;
  }
  .hosted-msg.assistant {
    align-self: flex-start; background: #fff; color: #111827;
    border: 1px solid #e5e7eb; border-bottom-left-radius: 4px;
  }
  .hosted-msg.error {
    align-self: flex-start; background: #fef2f2; color: #b91c1c;
    border: 1px solid #fecaca;
  }
  .hosted-msg.error.budget {
    background: #fffbeb; color: #92400e; border-color: #fde68a;
  }
  .hosted-msg.streaming::after {
    content: '▊'; animation: blink 0.7s steps(2) infinite; margin-left: 1px;
  }
  @keyframes blink { 50% { opacity: 0; } }

  .hosted-feedback-row { display: flex; gap: 4px; margin-top: 8px; }
  .hosted-fb-btn {
    background: none; border: 1px solid #e5e7eb; border-radius: 6px;
    padding: 2px 8px; font-size: 13px; cursor: pointer; color: #6b7280;
  }
  .hosted-fb-btn:hover { background: #f3f4f6; }
  .hosted-fb-btn.active { border-color: ${accent}; color: ${accent}; background: #eff6ff; }

  .hosted-typing { color: #9ca3af; font-size: 13px; padding: 4px 8px; }

  .hosted-footer {
    border-top: 1px solid #e5e7eb; padding: 12px 24px 8px; background: #fff;
  }
  .hosted-disclosure {
    font-size: 11px; color: #9ca3af; margin-bottom: 8px; line-height: 1.4;
  }
  .hosted-input-row {
    display: flex; gap: 10px;
  }
  .hosted-input-row input {
    flex: 1; border: 1px solid #d1d5db; border-radius: 10px;
    padding: 12px 14px; font-size: 14px; outline: none;
  }
  .hosted-input-row input:focus { border-color: ${accent}; box-shadow: 0 0 0 3px ${accent}22; }
  .hosted-input-row button {
    border: none; border-radius: 10px; padding: 12px 20px;
    background: ${accent}; color: #fff; font-size: 14px; font-weight: 500;
    cursor: pointer;
  }
  .hosted-input-row button:disabled { opacity: .5; cursor: default; }

  .hosted-char-count {
    display: block; text-align: right; font-size: 11px; color: #9ca3af; margin-top: 4px;
  }
  .hosted-char-count.warn { color: #f59e0b; }
  .hosted-char-count.over { color: #ef4444; }
  `;
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => {
    const map: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
    return map[ch];
  });
}

function escapeAttr(value: string): string {
  return value.replace(/[&"'<>]/g, (ch) => {
    const map: Record<string, string> = { '&': '&amp;', '"': '&quot;', "'": '&#39;', '<': '&lt;', '>': '&gt;' };
    return map[ch];
  });
}
