"""
P5-11 — Compliance posture (Arch §14, EU-AI-Act).

Art. 50 bot/AI-interaction disclosure, AI-generated-content marking on
exports, Art. 73 incident reporting hook, and the re-verification-status
surface used by ops. Disclosure text is configurable per surface but a
compliant default is always available.
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any, Mapping, Optional

DEFAULT_DISCLOSURE_TEXT = (
    "You are chatting with an AI assistant. "
    "Responses are generated by artificial intelligence."
)


def bot_disclosure(surface: Optional[Mapping[str, Any]] = None) -> str:
    """Art. 50 notice text (surface override or compliant default)."""
    if surface:
        override = surface.get("bot_disclosure") or surface.get("disclosure")
        if override:
            return str(override)
    return DEFAULT_DISCLOSURE_TEXT


def disclosure_payload(
    *,
    tenant_id: str,
    surface: Optional[Mapping[str, Any]] = None,
    surface_type: str = "widget",
) -> dict[str, Any]:
    """The API metadata block surfaces/widgets render for Art. 50."""
    return {
        "ai_disclosure": bot_disclosure(surface),
        "interaction_type": surface_type,
        "governance_version": "v1",
        "export_marked": True,
    }


def mark_export(export: dict[str, Any]) -> dict[str, Any]:
    """Mark an export bundle as containing AI-generated content (Art. 50).

    GDPR/DSR export bundles must carry the flag so a data subject knows some
    content is machine-produced.
    """
    export = dict(export)
    export["export_marked_ai_generated"] = True
    export["disclosure"] = DEFAULT_DISCLOSURE_TEXT
    return export


class ComplianceService:
    """Posture helpers: incident hook + re-verification cadence (D-6)."""

    def __init__(self, *, incident_hook=None, verified_on: date | None = None):
        self._incident_hook = incident_hook
        self._verified_on = verified_on or date(2026, 1, 1)

    def report_incident(self, *, tenant_id: str, severity: str, description: str) -> dict[str, Any]:
        """Record an Art. 73 incident; stateless hook (worker persistence
        is owned by the route, which calls AuditRepository)."""
        record = {
            "tenant_id": tenant_id,
            "severity": severity,
            "description": description,
            "reported_at": datetime.now(timezone.utc).isoformat(),
        }
        if self._incident_hook:
            self._incident_hook(record)
        return record

    def checklist(self, *, as_of: date | None = None) -> dict[str, Any]:
        """Compliance checklist as of the last re-verification date (D-6)."""
        as_of = as_of or self._verified_on
        check = {
            "disclosure_art50": True,
            "logging_art12": True,
            "human_oversight_art26": True,
            "post_market_monitoring_art72": "scheduled",  # P6-4
            "incident_reporting_art73": True,
            "deployer_documentation": False,
            "per_tenant_risk_assessment": False,
            "documented_adversarial_testing": False,
            "reverification_required_by": "2027-12-01",
        }
        return {
            "verified_on": as_of.isoformat(),
            "current": as_of >= self._verified_on,
            "checklist": check,
        }


def retention_days_for(tenant_config: Mapping[str, Any]) -> int:
    """Retention window (days) per tenant config; default per EU posture."""
    memory = tenant_config.get("memory") or {}
    expiry = memory.get("expiry_days")
    if expiry and expiry > 0:
        return int(expiry)
    return 30  # codebase default: memories.expiry_days